SERVER_IP: ${spring.cloud.client.ip-address}
server:
  port: ${SERVER_PORT:8081}
  ip: ${SERVER_IP}
  zone: ${ZONE:default}

spring:
  redis:
    timeout: 50000ms
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 2
        max-wait: 50000ms
    database: 0
    host: middleware.siupay.com
    port: 6379
  cloud:
    stream:
      kafka:
        binder:
          brokers: middleware.siupay.com:9092
          autoCreateTopics: false
      bindings:
        input:
          destination: PAYMENT_ACCEPTANCE_TOPIC
          group: kafka-group
          consumer:
            autoCommitOffset: true
            concurrency: 1
        output:
          destination: PAYMENT_ACCEPTANCE_TOPIC
          producer:
            sync: true

