SERVER_PORT: 8083




CONSUL_HOST: 10.178.85.227


REDIS_MASTER: xpay_redis_test_gz_001
REDIS_NODES: "grouptest1007-nw-sz-sentinel.yy.com:20008,grouptest1007-nw-sz-sentinel.yy.com:20008,grouptest1007-nw-bj-sentinel.yy.com:20008"
